categories:
- Synthetic Biology
description: Generate the RetroPath2.0 sink file from an SBML input
long_description: 'Sink refers to the collection of chemical species used by the restrosynthesis
  algorithm of RetroPath2.0 to finish metabolic route exploration. This tool uses
  an SBML file of the desired chassis organism, parses all the molecules within a
  specified compartment (example: cytoplasm, Golgi apparatus, nucleus, etc) and uses
  its MIRIAM annotation to find their InChI structures. Source code may be found at
  the following location: https://github.com/brsynth/rptools/tree/master/rptools/rpextractsink'
name: rpextractsink
owner: iuc
