name: rpfbagr
owner: iuc
description: Cli interface to predict gene knockout targets with an heterologous pathway
long_description: Cli interface to predict gene knockout targets with an heterologous pathway
homepage_url: https://github.com/brsynth/rpfbagr
remote_repository_url: https://github.com/brsynth/rpfbagr
categories:
  - Systems Biology
