categories:
- Synthetic Biology
description: Visualize pathways from the RetroPath Suite
homepage_url: https://github.com/brsynth/rptools/releases
long_description: 'Visualize pathways from the RetroPath Suite: https://www.sciencedirect.com/science/article/pii/S1096717617301337.'
name: rpviz
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/rpviz
