name: straindesign
owner: iuc
description: Cli interface to predict gene knockout targets with an heterologous pathway
long_description: Cli interface to predict gene knockout targets with an heterologous pathway
homepage_url: https://github.com/brsynth/straindesign
remote_repository_url: https://github.com/brsynth/straindesign
categories:
  - Systems Biology
  - Synthetic Biology
