categories:
- Synthetic Biology
description: Pathways HTML Report
homepage_url: https://github.com/brsynth/rptools/releases
long_description: 'Generates HTML report to explore the main characteristics of pathways
  predicted with RetroPath suite.'
name: rpreport
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/rpreport
