categories:
- Synthetic Biology
description: Rank heterologous pathways according to their global score
homepage_url: https://github.com/brsynth/rptools/releases
long_description: 'Rank heterologous pathways according to their global score.'
name: rpranker
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/rpranker
