categories:
- Synthetic Biology
description: Build a reaction network from a set of source compounds to a set of sink compounds
long_description: Perform retrosynthesis search of possible metabolic routes between a source molecule and a collection of sink molecules.  It takes for input the minimal (dmin) and maximal (dmax) diameter for the reaction rules and the maximal path length (maxSteps). The tool expects the following files: rules.csv, sink.csv and source.csv and produce a retrosynthesis network as a CSV file providing reactions in the reaction SMILES format and chemicals in both SMILES and InChI formats along with other information like the score for each reaction.
homepage_url: https://github.com/brsynth/RetroPath2-wrapper
name: RetroPath2.0
owner: iuc
