name: rp_fba_analysis
owner: iuc
description: Run OptGene, OptKnock with an heterologous pathway
homepage_url: https://github.com/brsynth/rpFbaAnalysis
long_description: 'Provides a cli interface to run OptGene, OptKnock with an heterologous pathway'
remote_repository_url: https://github.com/brsynth/rpFbaAnalysis
categories:
  - Systems Biology
